### PR TITLE
add amharic sbl

### PR DESCRIPTION
**Pull request by yosiasz**
Greetings,

Trying to get the snowball rolling 😄 on adding Amharic support. This is WIP as I have yet to do the ```routines``` part of Amharic which I need a lot of work and help on. But at least this gets things started.

Thanks

### CODE REVIEW

**Comment by yosiasz** [comment]
need a little more foundational work for this. learning as I go

**Comment by ojwb** [comment]
@yosiasz Did you get any further with your Amharic stemmer?

**Comment by yosiasz** [comment]
Thanks! It has been a while. I put this on hold for a while because there is a lot of foundational work that needs to happen for Geez based languages.

**Comment by ojwb** [comment]
OK - if you need any guidance on the snowball side, let us know.

**Pull request closed without merging**
