### PR TITLE
Optimized snowball code for tamil stemmer

### PR DESCRIPTION
**Pull request by rdamodharan**
I have replaced simple `or` conditions with `among()` command as suggested by Martin. I tried to use `among()` which consisted of some `test()` commands inside and they didnt work as expected so have left them as it is. I tested the modification against the data in https://github.com/rdamodharan/snowball-data/tree/master/tamil and the results were same.

### CODE REVIEW

**Comment by ojwb** [comment]
I'm trying to tidy up the licensing situation for snowball (see snowballstem/snowball#10 for more details).

Are you OK to license this patch under the 3-clause BSD licence shown here:

http://opensource.org/licenses/BSD-3-Clause

**Comment by ojwb** [comment]
The cause of the inconsistent results was a variable in the tamil snowball stemmer not being reset between runs (see snowballstem/snowball-data#1 for details).

**Comment by ojwb** [comment]
Currently waiting to hear about licensing.

Also waiting to hear if the altered output when the `found_vetrumai_urupu` variable is consistently cleared before each word is OK - 987 words in the testdata stem differently after this fix, but I am not familiar with Tamil so I can't tell if they're now handled better, worse, or similarly well.

**Comment by rdamodharan** [comment]
@ojwb I am extremely sorry for the delay in the response. 

Regarding the licensing I am fine with licensing the patch under 3-clause BSD. 

I have done some preliminary tests on the change you suggested and it looked fine to me. I will look more into it this weekend and confirm to you.

**Comment by ojwb** [comment]
No need to be sorry for taking time - it took us long enough to track down the issue that was causing the inconsistent stemming results!

Let me know if you've any questions I might be able to help with.

**Comment by rdamodharan** [comment]
I have checked some more outputs and I think the change proposed (unsetting found_vetrumai_urupu) gives more correct results.

**Comment by ojwb** [comment]
Thanks for checking - will get this merged soon.

**Comment by ojwb** [comment]
I rebased f5fc814937e6761c0688611de7b4a8845532c9eb onto the other branch so it was just a whitespace cleanup, and have merged the result.  Thanks.

Was there a reason to keep all the commented-out unused groupings in the code?

**Comment by rdamodharan** [comment]
Thank you Olly. I added it initially thinking I might need it but have not
used it. There is no reason to keep it now.

Damu

**Comment by ojwb** [comment]
Thanks for confirming.  All merged, so closing.

**Pull request closed without merging**
