### PR TITLE
fix GNUmakefile dependencies on Windows

### PR DESCRIPTION
**Pull request by jannick0**
On Windows platforms executables have the extension '.exe'.  Compilers
like gcc append the extension if not provided in the '-o' flag.  A Windows
platform can easily be recognized by checking if the environment variable
OS equals 'Windows_NT'.

This commit adds the extension of built executables to prerequisites of
GNUmakefile rules, such that make can figure out the dependencies.

NOTE: Extensions are not added to executable names when called by a shell
(e.g., cmd, sh) which are usually able to call the executable even when
the name is provided without extension.

### CODE REVIEW

**Comment by ojwb** [comment]
This looks reasonable, though without CI coverage I worry how long it would actually stay working for as this isn't a platform I use myself.

Would you be up for adding a CI build?  Apparently travis now supports it: https://docs.travis-ci.com/user/reference/windows/

**Comment by jannick0** [comment]
> Would you be up for adding a CI build? Apparently travis now supports it: https://docs.travis-ci.com/user/reference/windows/
I can try. This might pile up to a commit series while testing which I'll will ultimately squash. ... just as a heads-up. ;)

**Comment by ojwb** [comment]
Hmm, it seems to hit a 10 minute timeout trying to clone the snowball-data repo, even with `--depth=1`.  I'm guessing git on this platform is much slower with the large files in this repo.

I wonder if downloading the branch we want as a ZIP file and unpacking it would be a better option.  It looks like we didn't have the `.git` on `GH_REPO_URL` we'd could fetch `$GH_REPO_URL/archive/$GH_BRANCH.zip` to get the branch we want.

 Thoughts?

**Comment by jannick0** [comment]
Well, the issue rather is that travis' Windows support is beta.

**Comment by ojwb** [comment]
I managed to get this to work, and even passing the C tests.  It looks like the git clone issue got solved in the meantime.

None of the other languages get tested currently, but happy to take patches to address that (notably there's special handling for csharp in the changes here which doesn't get tested).

**Pull request closed without merging**
